version: '3'
services:
  postgres:
    image: postgres:15.0-alpine
    restart: always
    env_file: .env
    networks:
      - postgres
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    command: npm run dev
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres: