version: '3'
services:
  postgres:
    image: postgres:15.0-alpine
    restart: always
    env_file: .env
    networks:
      - postgres
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    command: npm run dev
    env_file: .env
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - postgres
    networks:
      - postgres
    volumes:
      - .:/usr/app
      - /usr/app/dist
      - /usr/app/node_modules

networks:
  postgres: